version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: scorpion
      POSTGRES_DB: inventaire
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mynetwork

  # nextjs-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nextjs_app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: postgres://postgres:scorpion@postgres_db:5432/inventaire
  #   depends_on:
  #     - postgres
  #   networks:
  #     - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:

